# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "vaxis_holder"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(37.9731, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr1():
	P000 = App.Vector(33.9776, -3.6000, 0)
	P001 = App.Vector(26.5660, -1.9523, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, -0.0000, 0)
	P003 = App.Vector(26.5660, 1.9523, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(33.9776, 3.6000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(35.2010, 4.4329, 0)
	P006 = App.Vector(35.5167, 5.8789, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(31.1769, 18.0000, 0)
	P008 = App.Vector(22.8497, 27.8189, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(21.4395, 28.2685, 0)
	P010 = App.Vector(20.1065, 27.6255, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(14.9738, 22.0307, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(12.5000, 21.6506, 0)
	P013 = App.Vector(11.5922, 23.9830, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(13.8711, 31.2254, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(13.7615, 32.7014, 0)
	P016 = App.Vector(12.6671, 33.6979, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(0.0000, 36.0000, 0)
	P018 = App.Vector(-12.6671, 33.6979, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-13.7615, 32.7014, 0)
	P020 = App.Vector(-13.8711, 31.2254, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-11.5922, 23.9830, 0)
	S012 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-12.5000, 21.6506, 0)
	P023 = App.Vector(-14.9738, 22.0307, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-20.1065, 27.6255, 0)
	S014 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-21.4395, 28.2685, 0)
	P026 = App.Vector(-22.8497, 27.8189, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-31.1769, 18.0000, 0)
	P028 = App.Vector(-35.5167, 5.8789, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-35.2010, 4.4329, 0)
	P030 = App.Vector(-33.9776, 3.6000, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-26.5660, 1.9523, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-25.0000, 0.0000, 0)
	P033 = App.Vector(-26.5660, -1.9523, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-33.9776, -3.6000, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-35.2010, -4.4329, 0)
	P036 = App.Vector(-35.5167, -5.8789, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-31.1769, -18.0000, 0)
	P038 = App.Vector(-22.8497, -27.8189, 0)
	S022 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-21.4395, -28.2685, 0)
	P040 = App.Vector(-20.1065, -27.6255, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-14.9738, -22.0307, 0)
	S024 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-12.5000, -21.6506, 0)
	P043 = App.Vector(-11.5922, -23.9830, 0)
	S025 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-13.8711, -31.2254, 0)
	S026 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-13.7615, -32.7014, 0)
	P046 = App.Vector(-12.6671, -33.6979, 0)
	S027 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(0.0000, -36.0000, 0)
	P048 = App.Vector(12.6671, -33.6979, 0)
	S028 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(13.7615, -32.7014, 0)
	P050 = App.Vector(13.8711, -31.2254, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(11.5922, -23.9830, 0)
	S030 = Part.LineSegment(P050, P051)
	P052 = App.Vector(12.5000, -21.6506, 0)
	P053 = App.Vector(14.9738, -22.0307, 0)
	S031 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(20.1065, -27.6255, 0)
	S032 = Part.LineSegment(P053, P054)
	P055 = App.Vector(21.4395, -28.2685, 0)
	P056 = App.Vector(22.8497, -27.8189, 0)
	S033 = Part.Arc(P054, P055, P056)
	P057 = App.Vector(31.1769, -18.0000, 0)
	P058 = App.Vector(35.5167, -5.8789, 0)
	S034 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(35.2010, -4.4329, 0)
	P060 = App.Vector(33.9776, -3.6000, 0)
	S035 = Part.Arc(P058, P059, P060)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, 23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-27.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_vaxis_holder_facePetal_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(13.5000, -23.3827, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_vaxis_holder_facePetal_Fa0():
	FC000 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr0()
	FC001 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr1()
	FC002 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr2()
	FC003 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr3()
	FC004 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr4()
	FC005 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr5()
	FC006 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr6()
	FC007 = ctr_face_vaxis_holder_facePetal_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def vaxis_holder_facePetal():
	FA000 = face_vaxis_holder_facePetal_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holder_faceOuter_Fa0_Ctr0():
	P000 = App.Vector(36.0000, -1.0000, 0)
	P001 = App.Vector(38.0255, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(38.2611, -9.9966, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(40.2604, -9.9442, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(39.7369, 10.0489, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(37.7375, 9.9966, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(37.9731, 1.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(36.0000, 1.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(36.0000, -1.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holder_faceOuter_Fa0():
	FC000 = ctr_face_vaxis_holder_faceOuter_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holder_faceOuter():
	FA000 = face_vaxis_holder_faceOuter_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holder_faceButtress1_Fa0_Ctr0():
	P000 = App.Vector(29.0000, -1.0000, 0)
	P001 = App.Vector(38.0255, -1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(38.2611, -9.9966, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(29.0000, -1.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holder_faceButtress1_Fa0():
	FC000 = ctr_face_vaxis_holder_faceButtress1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holder_faceButtress1():
	FA000 = face_vaxis_holder_faceButtress1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_vaxis_holder_faceButtress2_Fa0_Ctr0():
	P000 = App.Vector(29.0000, 1.0000, 0)
	P001 = App.Vector(37.9731, 1.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(37.7375, 9.9966, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(29.0000, 7.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(29.0000, 1.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_vaxis_holder_faceButtress2_Fa0():
	FC000 = ctr_face_vaxis_holder_faceButtress2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def vaxis_holder_faceButtress2():
	FA000 = face_vaxis_holder_faceButtress2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_vaxis_holder_outer():
	FIG = vaxis_holder_faceOuter()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_vaxis_holder_outer = fex_subpax_vaxis_holder_outer()

def fex_subpax_vaxis_holder_petal():
	FIG = vaxis_holder_facePetal()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, -1))
	return VFP
subpax_vaxis_holder_petal = fex_subpax_vaxis_holder_petal()

def fex_subpax_vaxis_holder_b1_0():
	FIG = vaxis_holder_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 1, 0))
	return VFP
subpax_vaxis_holder_b1_0 = fex_subpax_vaxis_holder_b1_0()

def fex_subpax_vaxis_holder_b1_1():
	FIG = vaxis_holder_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 59.99999999999999)
	VFP = VR3.translate(App.Vector(-0.8660254037844386, 0.5000000000000001, 0))
	return VFP
subpax_vaxis_holder_b1_1 = fex_subpax_vaxis_holder_b1_1()

def fex_subpax_vaxis_holder_b1_2():
	FIG = vaxis_holder_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.00000000000001)
	VFP = VR3.translate(App.Vector(-0.8660254037844387, -0.4999999999999998, 0))
	return VFP
subpax_vaxis_holder_b1_2 = fex_subpax_vaxis_holder_b1_2()

def fex_subpax_vaxis_holder_b1_3():
	FIG = vaxis_holder_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180)
	VFP = VR3.translate(App.Vector(-1.2246467991473532e-16, -1, 0))
	return VFP
subpax_vaxis_holder_b1_3 = fex_subpax_vaxis_holder_b1_3()

def fex_subpax_vaxis_holder_b1_4():
	FIG = vaxis_holder_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.00000000000004)
	VFP = VR3.translate(App.Vector(0.8660254037844385, -0.5000000000000004, 0))
	return VFP
subpax_vaxis_holder_b1_4 = fex_subpax_vaxis_holder_b1_4()

def fex_subpax_vaxis_holder_b1_5():
	FIG = vaxis_holder_faceButtress1()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.00000000000004)
	VFP = VR3.translate(App.Vector(0.866025403784439, 0.49999999999999933, 0))
	return VFP
subpax_vaxis_holder_b1_5 = fex_subpax_vaxis_holder_b1_5()

def fex_subpax_vaxis_holder_b2_0():
	FIG = vaxis_holder_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 1, 0))
	return VFP
subpax_vaxis_holder_b2_0 = fex_subpax_vaxis_holder_b2_0()

def fex_subpax_vaxis_holder_b2_1():
	FIG = vaxis_holder_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 59.99999999999999)
	VFP = VR3.translate(App.Vector(-0.8660254037844386, 0.5000000000000001, 0))
	return VFP
subpax_vaxis_holder_b2_1 = fex_subpax_vaxis_holder_b2_1()

def fex_subpax_vaxis_holder_b2_2():
	FIG = vaxis_holder_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 120.00000000000001)
	VFP = VR3.translate(App.Vector(-0.8660254037844387, -0.4999999999999998, 0))
	return VFP
subpax_vaxis_holder_b2_2 = fex_subpax_vaxis_holder_b2_2()

def fex_subpax_vaxis_holder_b2_3():
	FIG = vaxis_holder_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180)
	VFP = VR3.translate(App.Vector(-1.2246467991473532e-16, -1, 0))
	return VFP
subpax_vaxis_holder_b2_3 = fex_subpax_vaxis_holder_b2_3()

def fex_subpax_vaxis_holder_b2_4():
	FIG = vaxis_holder_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -120.00000000000004)
	VFP = VR3.translate(App.Vector(0.8660254037844385, -0.5000000000000004, 0))
	return VFP
subpax_vaxis_holder_b2_4 = fex_subpax_vaxis_holder_b2_4()

def fex_subpax_vaxis_holder_b2_5():
	FIG = vaxis_holder_faceButtress2()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -60.00000000000004)
	VFP = VR3.translate(App.Vector(0.866025403784439, 0.49999999999999933, 0))
	return VFP
subpax_vaxis_holder_b2_5 = fex_subpax_vaxis_holder_b2_5()

pax_vaxis_holder = subpax_vaxis_holder_petal.fuse([subpax_vaxis_holder_outer, subpax_vaxis_holder_b1_0, subpax_vaxis_holder_b1_1, subpax_vaxis_holder_b1_2, subpax_vaxis_holder_b1_3, subpax_vaxis_holder_b1_4, subpax_vaxis_holder_b1_5, subpax_vaxis_holder_b2_0, subpax_vaxis_holder_b2_1, subpax_vaxis_holder_b2_2, subpax_vaxis_holder_b2_3, subpax_vaxis_holder_b2_4, subpax_vaxis_holder_b2_5])

pax_vaxis_holder.check()
#pax_vaxis_holder.exportBrep(f"{outFileName}.brep")
#pax_vaxis_holder.exportIges(f"{outFileName}.igs")
#pax_vaxis_holder.exportStep(f"{outFileName}.stp")
pax_vaxis_holder.exportStl(f"{outFileName}.stl")

