// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_surface_faceSurface_Fa000_Ctr000 = polygon({ points: [ [ -204.0000, -181.0000 ],
	[ -124.0000, -181.0000 ],
	[ -124.0000, -131.0000 ],
	[ -204.0000, -131.0000 ],
	[ -204.0000, -181.0000 ] ] });

face_fig_surface_faceSurface_Fa000 = ctr_face_fig_surface_faceSurface_Fa000_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa001_Ctr000 = polygon({ points: [ [ -204.0000, -129.0000 ],
	[ -124.0000, -129.0000 ],
	[ -124.0000, -79.0000 ],
	[ -204.0000, -79.0000 ],
	[ -204.0000, -129.0000 ] ] });

face_fig_surface_faceSurface_Fa001 = ctr_face_fig_surface_faceSurface_Fa001_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa002_Ctr000 = polygon({ points: [ [ -204.0000, -77.0000 ],
	[ -124.0000, -77.0000 ],
	[ -124.0000, -27.0000 ],
	[ -204.0000, -27.0000 ],
	[ -204.0000, -77.0000 ] ] });

face_fig_surface_faceSurface_Fa002 = ctr_face_fig_surface_faceSurface_Fa002_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa003_Ctr000 = polygon({ points: [ [ -204.0000, -25.0000 ],
	[ -124.0000, -25.0000 ],
	[ -124.0000, 25.0000 ],
	[ -204.0000, 25.0000 ],
	[ -204.0000, -25.0000 ] ] });

face_fig_surface_faceSurface_Fa003 = ctr_face_fig_surface_faceSurface_Fa003_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa004_Ctr000 = polygon({ points: [ [ -204.0000, 27.0000 ],
	[ -124.0000, 27.0000 ],
	[ -124.0000, 77.0000 ],
	[ -204.0000, 77.0000 ],
	[ -204.0000, 27.0000 ] ] });

face_fig_surface_faceSurface_Fa004 = ctr_face_fig_surface_faceSurface_Fa004_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa005_Ctr000 = polygon({ points: [ [ -204.0000, 79.0000 ],
	[ -124.0000, 79.0000 ],
	[ -124.0000, 129.0000 ],
	[ -204.0000, 129.0000 ],
	[ -204.0000, 79.0000 ] ] });

face_fig_surface_faceSurface_Fa005 = ctr_face_fig_surface_faceSurface_Fa005_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa006_Ctr000 = polygon({ points: [ [ -204.0000, 131.0000 ],
	[ -124.0000, 131.0000 ],
	[ -124.0000, 181.0000 ],
	[ -204.0000, 181.0000 ],
	[ -204.0000, 131.0000 ] ] });

face_fig_surface_faceSurface_Fa006 = ctr_face_fig_surface_faceSurface_Fa006_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa007_Ctr000 = polygon({ points: [ [ -122.0000, -181.0000 ],
	[ -42.0000, -181.0000 ],
	[ -42.0000, -131.0000 ],
	[ -122.0000, -131.0000 ],
	[ -122.0000, -181.0000 ] ] });

face_fig_surface_faceSurface_Fa007 = ctr_face_fig_surface_faceSurface_Fa007_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa008_Ctr000 = polygon({ points: [ [ -122.0000, -129.0000 ],
	[ -42.0000, -129.0000 ],
	[ -42.0000, -79.0000 ],
	[ -122.0000, -79.0000 ],
	[ -122.0000, -129.0000 ] ] });

face_fig_surface_faceSurface_Fa008 = ctr_face_fig_surface_faceSurface_Fa008_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa009_Ctr000 = polygon({ points: [ [ -122.0000, -77.0000 ],
	[ -42.0000, -77.0000 ],
	[ -42.0000, -27.0000 ],
	[ -122.0000, -27.0000 ],
	[ -122.0000, -77.0000 ] ] });

face_fig_surface_faceSurface_Fa009 = ctr_face_fig_surface_faceSurface_Fa009_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa010_Ctr000 = polygon({ points: [ [ -122.0000, -25.0000 ],
	[ -42.0000, -25.0000 ],
	[ -42.0000, 25.0000 ],
	[ -122.0000, 25.0000 ],
	[ -122.0000, -25.0000 ] ] });

face_fig_surface_faceSurface_Fa010 = ctr_face_fig_surface_faceSurface_Fa010_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa011_Ctr000 = polygon({ points: [ [ -122.0000, 27.0000 ],
	[ -42.0000, 27.0000 ],
	[ -42.0000, 77.0000 ],
	[ -122.0000, 77.0000 ],
	[ -122.0000, 27.0000 ] ] });

face_fig_surface_faceSurface_Fa011 = ctr_face_fig_surface_faceSurface_Fa011_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa012_Ctr000 = polygon({ points: [ [ -122.0000, 79.0000 ],
	[ -42.0000, 79.0000 ],
	[ -42.0000, 129.0000 ],
	[ -122.0000, 129.0000 ],
	[ -122.0000, 79.0000 ] ] });

face_fig_surface_faceSurface_Fa012 = ctr_face_fig_surface_faceSurface_Fa012_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa013_Ctr000 = polygon({ points: [ [ -122.0000, 131.0000 ],
	[ -42.0000, 131.0000 ],
	[ -42.0000, 181.0000 ],
	[ -122.0000, 181.0000 ],
	[ -122.0000, 131.0000 ] ] });

face_fig_surface_faceSurface_Fa013 = ctr_face_fig_surface_faceSurface_Fa013_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa014_Ctr000 = polygon({ points: [ [ -40.0000, -181.0000 ],
	[ 40.0000, -181.0000 ],
	[ 40.0000, -131.0000 ],
	[ -40.0000, -131.0000 ],
	[ -40.0000, -181.0000 ] ] });

face_fig_surface_faceSurface_Fa014 = ctr_face_fig_surface_faceSurface_Fa014_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa015_Ctr000 = polygon({ points: [ [ -40.0000, -129.0000 ],
	[ 40.0000, -129.0000 ],
	[ 40.0000, -79.0000 ],
	[ -40.0000, -79.0000 ],
	[ -40.0000, -129.0000 ] ] });

face_fig_surface_faceSurface_Fa015 = ctr_face_fig_surface_faceSurface_Fa015_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa016_Ctr000 = polygon({ points: [ [ -40.0000, -77.0000 ],
	[ 40.0000, -77.0000 ],
	[ 40.0000, -27.0000 ],
	[ -40.0000, -27.0000 ],
	[ -40.0000, -77.0000 ] ] });

face_fig_surface_faceSurface_Fa016 = ctr_face_fig_surface_faceSurface_Fa016_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa017_Ctr000 = polygon({ points: [ [ -40.0000, -25.0000 ],
	[ 40.0000, -25.0000 ],
	[ 40.0000, 25.0000 ],
	[ -40.0000, 25.0000 ],
	[ -40.0000, -25.0000 ] ] });

face_fig_surface_faceSurface_Fa017 = ctr_face_fig_surface_faceSurface_Fa017_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa018_Ctr000 = polygon({ points: [ [ -40.0000, 27.0000 ],
	[ 40.0000, 27.0000 ],
	[ 40.0000, 77.0000 ],
	[ -40.0000, 77.0000 ],
	[ -40.0000, 27.0000 ] ] });

face_fig_surface_faceSurface_Fa018 = ctr_face_fig_surface_faceSurface_Fa018_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa019_Ctr000 = polygon({ points: [ [ -40.0000, 79.0000 ],
	[ 40.0000, 79.0000 ],
	[ 40.0000, 129.0000 ],
	[ -40.0000, 129.0000 ],
	[ -40.0000, 79.0000 ] ] });

face_fig_surface_faceSurface_Fa019 = ctr_face_fig_surface_faceSurface_Fa019_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa020_Ctr000 = polygon({ points: [ [ -40.0000, 131.0000 ],
	[ 40.0000, 131.0000 ],
	[ 40.0000, 181.0000 ],
	[ -40.0000, 181.0000 ],
	[ -40.0000, 131.0000 ] ] });

face_fig_surface_faceSurface_Fa020 = ctr_face_fig_surface_faceSurface_Fa020_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa021_Ctr000 = polygon({ points: [ [ 42.0000, -181.0000 ],
	[ 122.0000, -181.0000 ],
	[ 122.0000, -131.0000 ],
	[ 42.0000, -131.0000 ],
	[ 42.0000, -181.0000 ] ] });

face_fig_surface_faceSurface_Fa021 = ctr_face_fig_surface_faceSurface_Fa021_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa022_Ctr000 = polygon({ points: [ [ 42.0000, -129.0000 ],
	[ 122.0000, -129.0000 ],
	[ 122.0000, -79.0000 ],
	[ 42.0000, -79.0000 ],
	[ 42.0000, -129.0000 ] ] });

face_fig_surface_faceSurface_Fa022 = ctr_face_fig_surface_faceSurface_Fa022_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa023_Ctr000 = polygon({ points: [ [ 42.0000, -77.0000 ],
	[ 122.0000, -77.0000 ],
	[ 122.0000, -27.0000 ],
	[ 42.0000, -27.0000 ],
	[ 42.0000, -77.0000 ] ] });

face_fig_surface_faceSurface_Fa023 = ctr_face_fig_surface_faceSurface_Fa023_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa024_Ctr000 = polygon({ points: [ [ 42.0000, -25.0000 ],
	[ 122.0000, -25.0000 ],
	[ 122.0000, 25.0000 ],
	[ 42.0000, 25.0000 ],
	[ 42.0000, -25.0000 ] ] });

face_fig_surface_faceSurface_Fa024 = ctr_face_fig_surface_faceSurface_Fa024_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa025_Ctr000 = polygon({ points: [ [ 42.0000, 27.0000 ],
	[ 122.0000, 27.0000 ],
	[ 122.0000, 77.0000 ],
	[ 42.0000, 77.0000 ],
	[ 42.0000, 27.0000 ] ] });

face_fig_surface_faceSurface_Fa025 = ctr_face_fig_surface_faceSurface_Fa025_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa026_Ctr000 = polygon({ points: [ [ 42.0000, 79.0000 ],
	[ 122.0000, 79.0000 ],
	[ 122.0000, 129.0000 ],
	[ 42.0000, 129.0000 ],
	[ 42.0000, 79.0000 ] ] });

face_fig_surface_faceSurface_Fa026 = ctr_face_fig_surface_faceSurface_Fa026_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa027_Ctr000 = polygon({ points: [ [ 42.0000, 131.0000 ],
	[ 122.0000, 131.0000 ],
	[ 122.0000, 181.0000 ],
	[ 42.0000, 181.0000 ],
	[ 42.0000, 131.0000 ] ] });

face_fig_surface_faceSurface_Fa027 = ctr_face_fig_surface_faceSurface_Fa027_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa028_Ctr000 = polygon({ points: [ [ 124.0000, -181.0000 ],
	[ 204.0000, -181.0000 ],
	[ 204.0000, -131.0000 ],
	[ 124.0000, -131.0000 ],
	[ 124.0000, -181.0000 ] ] });

face_fig_surface_faceSurface_Fa028 = ctr_face_fig_surface_faceSurface_Fa028_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa029_Ctr000 = polygon({ points: [ [ 124.0000, -129.0000 ],
	[ 204.0000, -129.0000 ],
	[ 204.0000, -79.0000 ],
	[ 124.0000, -79.0000 ],
	[ 124.0000, -129.0000 ] ] });

face_fig_surface_faceSurface_Fa029 = ctr_face_fig_surface_faceSurface_Fa029_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa030_Ctr000 = polygon({ points: [ [ 124.0000, -77.0000 ],
	[ 204.0000, -77.0000 ],
	[ 204.0000, -27.0000 ],
	[ 124.0000, -27.0000 ],
	[ 124.0000, -77.0000 ] ] });

face_fig_surface_faceSurface_Fa030 = ctr_face_fig_surface_faceSurface_Fa030_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa031_Ctr000 = polygon({ points: [ [ 124.0000, -25.0000 ],
	[ 204.0000, -25.0000 ],
	[ 204.0000, 25.0000 ],
	[ 124.0000, 25.0000 ],
	[ 124.0000, -25.0000 ] ] });

face_fig_surface_faceSurface_Fa031 = ctr_face_fig_surface_faceSurface_Fa031_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa032_Ctr000 = polygon({ points: [ [ 124.0000, 27.0000 ],
	[ 204.0000, 27.0000 ],
	[ 204.0000, 77.0000 ],
	[ 124.0000, 77.0000 ],
	[ 124.0000, 27.0000 ] ] });

face_fig_surface_faceSurface_Fa032 = ctr_face_fig_surface_faceSurface_Fa032_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa033_Ctr000 = polygon({ points: [ [ 124.0000, 79.0000 ],
	[ 204.0000, 79.0000 ],
	[ 204.0000, 129.0000 ],
	[ 124.0000, 129.0000 ],
	[ 124.0000, 79.0000 ] ] });

face_fig_surface_faceSurface_Fa033 = ctr_face_fig_surface_faceSurface_Fa033_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa034_Ctr000 = polygon({ points: [ [ 124.0000, 131.0000 ],
	[ 204.0000, 131.0000 ],
	[ 204.0000, 181.0000 ],
	[ 124.0000, 181.0000 ],
	[ 124.0000, 131.0000 ] ] });

face_fig_surface_faceSurface_Fa034 = ctr_face_fig_surface_faceSurface_Fa034_Ctr000;
fig_surface_faceSurface = union( face_fig_surface_faceSurface_Fa000, face_fig_surface_faceSurface_Fa001, face_fig_surface_faceSurface_Fa002, face_fig_surface_faceSurface_Fa003, face_fig_surface_faceSurface_Fa004, face_fig_surface_faceSurface_Fa005, face_fig_surface_faceSurface_Fa006, face_fig_surface_faceSurface_Fa007, face_fig_surface_faceSurface_Fa008, face_fig_surface_faceSurface_Fa009, face_fig_surface_faceSurface_Fa010, face_fig_surface_faceSurface_Fa011, face_fig_surface_faceSurface_Fa012, face_fig_surface_faceSurface_Fa013, face_fig_surface_faceSurface_Fa014, face_fig_surface_faceSurface_Fa015, face_fig_surface_faceSurface_Fa016, face_fig_surface_faceSurface_Fa017, face_fig_surface_faceSurface_Fa018, face_fig_surface_faceSurface_Fa019, face_fig_surface_faceSurface_Fa020, face_fig_surface_faceSurface_Fa021, face_fig_surface_faceSurface_Fa022, face_fig_surface_faceSurface_Fa023, face_fig_surface_faceSurface_Fa024, face_fig_surface_faceSurface_Fa025, face_fig_surface_faceSurface_Fa026, face_fig_surface_faceSurface_Fa027, face_fig_surface_faceSurface_Fa028, face_fig_surface_faceSurface_Fa029, face_fig_surface_faceSurface_Fa030, face_fig_surface_faceSurface_Fa031, face_fig_surface_faceSurface_Fa032, face_fig_surface_faceSurface_Fa033, face_fig_surface_faceSurface_Fa034 );
const ctr_face_fig_surface_faceOnePanel_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 80.0000, 0.0000 ],
	[ 80.0000, 50.0000 ],
	[ 0.0000, 50.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_surface_faceOnePanel_Fa000 = ctr_face_fig_surface_faceOnePanel_Fa000_Ctr000;
fig_surface_faceOnePanel = face_fig_surface_faceOnePanel_Fa000;

const subpax_surface_panel_0 =
	translate( [ -204, -181, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_1 =
	translate( [ -204, -129, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_2 =
	translate( [ -204, -77, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_3 =
	translate( [ -204, -25, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_4 =
	translate( [ -204, 27, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_5 =
	translate( [ -204, 79, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_6 =
	translate( [ -204, 131, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_7 =
	translate( [ -122, -181, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_8 =
	translate( [ -122, -129, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_9 =
	translate( [ -122, -77, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_10 =
	translate( [ -122, -25, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_11 =
	translate( [ -122, 27, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_12 =
	translate( [ -122, 79, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_13 =
	translate( [ -122, 131, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_14 =
	translate( [ -40, -181, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_15 =
	translate( [ -40, -129, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_16 =
	translate( [ -40, -77, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_17 =
	translate( [ -40, -25, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_18 =
	translate( [ -40, 27, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_19 =
	translate( [ -40, 79, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_20 =
	translate( [ -40, 131, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_21 =
	translate( [ 42, -181, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_22 =
	translate( [ 42, -129, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_23 =
	translate( [ 42, -77, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_24 =
	translate( [ 42, -25, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_25 =
	translate( [ 42, 27, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_26 =
	translate( [ 42, 79, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_27 =
	translate( [ 42, 131, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_28 =
	translate( [ 124, -181, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_29 =
	translate( [ 124, -129, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_30 =
	translate( [ 124, -77, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_31 =
	translate( [ 124, -25, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_32 =
	translate( [ 124, 27, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_33 =
	translate( [ 124, 79, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_34 =
	translate( [ 124, 131, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 1}, fig_surface_faceOnePanel )
		)
	);

const pax_surface = union( subpax_surface_panel_0, subpax_surface_panel_1, subpax_surface_panel_2, subpax_surface_panel_3, subpax_surface_panel_4, subpax_surface_panel_5, subpax_surface_panel_6, subpax_surface_panel_7, subpax_surface_panel_8, subpax_surface_panel_9, subpax_surface_panel_10, subpax_surface_panel_11, subpax_surface_panel_12, subpax_surface_panel_13, subpax_surface_panel_14, subpax_surface_panel_15, subpax_surface_panel_16, subpax_surface_panel_17, subpax_surface_panel_18, subpax_surface_panel_19, subpax_surface_panel_20, subpax_surface_panel_21, subpax_surface_panel_22, subpax_surface_panel_23, subpax_surface_panel_24, subpax_surface_panel_25, subpax_surface_panel_26, subpax_surface_panel_27, subpax_surface_panel_28, subpax_surface_panel_29, subpax_surface_panel_30, subpax_surface_panel_31, subpax_surface_panel_32, subpax_surface_panel_33, subpax_surface_panel_34 );

return pax_surface;
}
module.exports = { main };
